### PR TITLE
Add Option to use Release Types (major, minor, patch) for Updates

### PR DESCRIPTION
**Pull request by saadmk11**
closes https://github.com/saadmk11/github-actions-version-updater/issues/22

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Awesome, thank you :)

**Comment by saadmk11** [comment]
> Awesome, thank you :)

Hi @SebastianStehle, Please try it out and let me know if this is working for you or not :)

**Comment by SebastianStehle** [comment]
Yes and no. I think the PR should only propose short versions for "major" ... like "@v2" and so on.

See: https://github.com/notifo-io/notifo/pull/135/files

**Comment by SebastianStehle** [comment]
Could also be another setting.

**Comment by saadmk11** [comment]
> Yes and no. I think the PR should only propose short versions for "major" ... like "@v2" and so on.
> 
> See: https://github.com/notifo-io/notifo/pull/135/files

Not all actions follow this pattern, and I think using specific tags than a moving tag is better because we know this will always run the same code.

**Comment by saadmk11** [comment]
> Btw: Can you not prebuilt the docker image? (I have no idea how docker actions work)

Yes, you can.

**Comment by SebastianStehle** [comment]
Therefore you have semantic versioning ;)

I would just prefer to get the small improvements and non breaking changes automatically.

**Comment by saadmk11** [comment]
> Therefore you have semantic versioning ;)
> 
> I would just prefer to get the small improvements and non breaking changes automatically.

GitHub is not actually using Semantic Versioning to find the version of an action, it is using Git Tags in case of `@v2`. So, `v2` is not equal to `v2.0.0` & `< v3.0.0` (like some package managers). The author of the action decides to create a moving tag (e.g.: `v2`) which is moved after every release of `v2.x.x`. But it is entirely up to the author and not every action follows this rule.

> If the action publishes major version tags, you should expect to receive critical fixes and security patches while still retaining compatibility. Note that this behavior is at the discretion of the action's author.

ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Pull request merged**
